### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by hellothisistim** [hellothisistim/bgNukes#1]
Needs testing on windows. If you can help, please drop me a line. Otherwise, you're just going to have to wait until I can get some time on a windows box.

**Comment by timbowman** [comment]
Here's some code that's working for me on Windows & nuke9.0v5

        cmd = " ".join([nuke.env['ExecutablePath'], flags, '-F', '"' + instRange + '"', nuke.value("root.name")])
        print ">>> starting instance %d" % (i, )
        print "command: " + cmd
        subprocess.Popen(cmd, shell=False)

I've taken out the parts that try to save the log because that dies horribly. And switched shell to False.
